server:
  port: 9091
spring:
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 29003
      username: "bilgeadam"
      password: "adminservice"
      database: "adminDB"
jwt:
  secretKey: ${PASSWORD}