server:
  port: 9094

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 29003
      username: "bilgeadam"
      password: "companyservice"
      database: "companyDB"

jwt:
  secretKey: ${PASSWORD}