server:
  port: 9092
spring:
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 29003
      username: "bilgeadam"
      password: "managerservice"
      database: "managerDB"

jwt:
  secretKey: ${PASSWORD}