server:
  port: 9093
spring:
  data:
    mongodb:
      host: localhost
      port: 29003
      username: "bilgeadam"
      password: "userservice"
      database: "userDB"

jwt:
  secretKey: ${PASSWORD}